# docker-compose -p webglace up -d

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-20210607
    container_name: selenium_for_webglace
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: "2g"
    depends_on:
      - webglace_shiny
    networks:
      - selenium-net

  novnc:
    image: jspowley/novnc:latest
    container_name: novnc_for_webglace
    ports:
      - "6900:6900"
    depends_on:
      - selenium
    networks:
      - selenium-net
      
  webglace_shiny:
    image: jspowley/webglace_shiny:latest
    container_name: shiny_for_webglace
    ports:
      - "3838:3838"
    networks:
      - selenium-net
    pull_policy: always

networks:
  selenium-net:
    driver: bridge
